<!doctype html>

<html lang="en">

<head>

	<meta charset="UTF-8">
	<title>Yale School of Art</title>
	<link rel="stylesheet" type="text/css" href="YaleArt.css">

</head>

<body>
<a href="javascript:void(0);" id="MobileMenuButton" class="mobileMenu" onclick="openNav()">&#9776;</a>
<script>
function openNav() {
    document.getElementById("Menu").style.width = "37%";
	document.getElementById("MobileMenuButton").style.visibility = "hidden";
}

function closeNav() {
    document.getElementById("Menu").style.width = "0";
	document.getElementById("MobileMenuButton").style.visibility = "visible";
}
</script>
<a href="YaleArt.php"><img id = "logo" src="logo.png"></a>
 <h1 class="Text">Yale School of Art</h1>
<button class="LoginButton"onclick="window.location.href='login.php'">Login</button>
<a href="login.php"><img class="mobileLoginButton" src="mobileLogin.png"></a>
  <br class="clear">
  <br>
  <div class="navbar" id="Menu">
	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
	<div class="dropdown">
    <button class="dropbtn">Faculty 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="#">Facilities </a>
	  <a href="#">Faculty & Staff </a>
    </div>
  </div> 
  <div class="dropdown">
    <button class="dropbtn">Visiting
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="#">Admissions</a>
	  <a href="#">Calenders</a>
	   <a href="#">Courses</a>
      <a href="#">Current Students</a>
    </div>
  </div> 
  <div class="dropdown">
    <button class="dropbtn">Students 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="#">Courses  </a>
      <a href="#">Financial Aid </a>
      <a href="#">Recent Changes</a>
    </div>
  </div> 
  <div class="dropdown">
    <button class="dropbtn"> Gallery
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="#">Exhibitions</a>
      <a href="#">Gallery Schedules</a>
    </div>
  </div> 
  <div class="dropdown">
    <button class="dropbtn">Alums
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="#">After Graduation</a>
      <a href="#">Mentoring Program</a>
      <a href="#">Newsletter</a>
    </div>
  </div> 
    </div>
  <br>
  <br>
  <h1 class="mobileText"> Welcome to the Yale School of Art</h1>
  <br>
  
<div class="container">
<img class="Slideshow" src="Painting2.jpg" height="400" >
<img class="Slideshow" src="Building.jpg" height="400" >
<img class="Slideshow" src="Sign.jpg" height="400" >
<img class="Slideshow" src="Painting.jpg" height="400" width="800">
<img class="Slideshow" src="History.jpg" height="400" >
<button class="lbtn" onclick="plusDivs(-1)">&#10094;</button>
<button class="rbtn" onclick="plusDivs(+1)">&#10095;</button>
</div>
<br>
<script>
var slideIndex = 0;
showDivs(slideIndex);
carousel();
function plusDivs(n) {
    showDivs(slideIndex += n);
}
function showDivs(n) {
    var i;
    var x = document.getElementsByClassName("Slideshow");
    if (n > x.length) {slideIndex = 1} 
    if (n < 1) {slideIndex = x.length} ;
    for (i = 0; i < x.length; i++) {
        x[i].style.display = "none"; 
    }
    x[slideIndex-1].style.display = "block"; 
}
function carousel() {
    var i;
    var x = document.getElementsByClassName("Slideshow");
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none"; 
    }
    slideIndex++;
    if (slideIndex > x.length) {slideIndex = 1} 
    x[slideIndex-1].style.display = "block"; 
    setTimeout(carousel, 4000);
}
</script>
<br>

<p class="intro"> The School of Art offers professional instruction in four interrelated areas of study: graphic design, painting/printmaking, photography, and sculpture. Artists and designers of unusual promise and strong motivation are provided an educational context in which they can explore the potential of their own talents in the midst of an intense critical dialogue. This dialogue is generated by their peers, by distinguished visitors, and by a faculty comprised of professional artists of acknowledged accomplishment. </p>
<p class="intro2">The graduate student’s primary educational experience at Yale is centered on his or her own studio activity. Supporting this enterprise are the experience, knowledge, and skills gained from rigorous, structured courses such as drawing, filmmaking, the relativity of color, and the rich academic offerings found throughout Yale. Each student is routinely exposed to many aesthetic positions through encounters with faculty members and visitors. The School is devoted not only to the refinement of visual skills, but to the cultivation of the mind. Students must bring creative force and imagination to their own development, for these qualities cannot be taught—they can only be stimulated and appreciated.The School of Art offers an undergraduate art major for students in Yale College (see the bulletin Yale College Programs of Study). In addition, the School’s courses are open to students in the Graduate School and other professional schools of the University, and School of Art students may enroll in elective courses in the Graduate School and other professional schools as well as in the College with permission.</p>

<br>
<br>
<br>
<br>
<div class="footer">
  <a href="#" class = "footer-button"> About Us</a> 
  <a href="#"class = "footer-button"> Contact Us</a> 
</div>

	

</body>

</html>
